sudo: required
services:
  - docker

before_install:
  - docker build -t crabjuice/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true crabjuice/react-test npm test

after_success:
  - docker build - crabjuice/multi-client ./client
  - docker build - crabjuice/multi-nginx ./nginx
  - docker build - crabjuice/multi-server ./server
  - docker build - crabjuice/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push crabjuice/multi-client
  - docker push crabjuice/multi-nginx
  - docker push crabjuice/multi-server
  - docker push crabjuice/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-479538108586'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
